apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientsnttpf
  labels:
    app: clientsnttpf
spec:
  replicas: 1
  selector:
    matchLabels:
      service: clientsnttpf
  template:
    metadata:
      labels:
        app: clientsnttpf
        service: clientsnttpf
    spec:
      containers:
        - name: clientsnttpf
          image: clientsnttpf.azurecr.io/clientsnttpf:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: WebApiBaseAddress
              value: http://webapi