apiVersion: v1
kind: Service
metadata:
  name: clientsnttpf
  labels:
    app: clientsnttpf
    service: clientsnttpf
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    service: clientsnttpf